function rvr_add_sec
f = figure('Name','RIVeR - Add Section',...
    'ToolBar','none',...
    'MenuBar','none',...
    'IntegerHandle','off',...
    'Resize','off',...
    'Tag','fig_crs');
f.Position(3)=365;f.Position(4)=146;
str=uicontrol('Position',[15 115 200 21],...
    'Style','text',...
    'String','Cross Section coordinates. UTM zone:',...
    'Tag','str');
utmzone=uicontrol('Position',[210 85 30 18],...
    'Style','edit',...
    'String','20 H',...
    'Tag','utmzone');
% % create the data
cnames = {'East-Data','North-Data'};
%
% if isempty(actual_M)==1
d = [0 0; 0 0];
rnames = {'L','R'};

% Create the uitable
t = uitable(f,'Data',d,...
    'ColumnName',cnames,...
    'RowName',rnames,...
    'Enable','on',...
    'ColumnEditable',[true, true],...
    'CellSelectionCallback',@(src,evnt)set(src,'UserData',evnt.Indices),...
    'Tag','table');

t.Position(3) = 182;
t.Position(4) = 19.1*(size(rnames,2)+1);
f.Position(4)=t.Position(4)+46;
str.Position(2)=f.Position(4)-24.1;

%Create a button to import from excel
bt_xls=uicontrol('Position',[0.5 0.5 100 21],...
    'Style','pushbutton',...
    'String','Import from Excel',...
    'Callback',@imp_cp);
bt_xls.Position(1) = 250;
bt_xls.Position(2) = f.Position(4)-26-2*(19.1+ 3);

%Create a button to apply
bt_apply=uicontrol('Position',[0.5 0.5 100 21],...
    'Style','pushbutton',...
    'String','Apply',...
    'Callback',@apply);
bt_apply.Position(1) = 250;
bt_apply.Position(2) = f.Position(4)-26-3*(19.1+ 3);

function imp_cp(hObject,eventdata)
[FileName PathName]=uigetfile({'*.xls';'*.xlsx';'*.*'},'Select a file');
if FileName~=0
    Data=xlsread([PathName FileName]);
    table=findobj('Tag','table');
    f=gcf;
    cnames = {'East-Data','North-Data'};
    
    
    rnames{1} ='L';
    rnames{2} ='R';
    
    set(table,'Data',Data(1:2,1:2),...
        'ColumnName',cnames,...
        'RowName',rnames,...
        'Enable','on',...
        'ColumnEditable',[true, true],...
        'CellSelectionCallback',@(src,evnt)set(src,'UserData',evnt.Indices),...
        'Tag','table');
    
end

function apply(hObject,eventdata)
f=gcf;
table=findobj('Tag','table');
utmzone=findobj('Tag','utmzone');
Data=get(table,'Data');
utmzone=get(utmzone,'String');

CS=[Data; ones(1,size(Data,1))];
dummy=figure('Tag','dummy','Visible','off');
guidata(dummy,struct('CS',CS,'utmzone',utmzone));

close(f);
